repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: debug-statements
          - id: name-tests-test
          - id: requirements-txt-fixer
          - id: detect-private-key
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
    - repo: https://github.com/PyCQA/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args:
                [
                    --in-place,
                    --remove-all-unused-imports,
                    --remove-unused-variables,
                    --recursive,
                    .,
                ]
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: https://github.com/python/black
      rev: 22.3.0
      hooks:
          - id: black
            args:
                - --line-length=88
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
