# conversion to cartesian coordinates config
scan_to_xy:
  angle_min: -2.356194
  angle_max:  2.356194
  angle_inc:  0.004363
  pps: 1081

# pseudo vision occupancy grid config
occ_grid:
  resolution: 8
  map_size: 64
  centered: false
  marker: true

# data colletion
data_collection:
  sub_topic: '/vesc/low_level/ackermann_cmd_mux/input/teleop'
  pub_topic: '/train_data'

# model config
pseudo_vision_fcnn:
  input_size: 64
  classes: 3
  n_layers: 3
  weights: '/home/ychau001/Desktop/best-results-epoch=5-val_acc1=0.82.ckpt'
  speed: 3.0

pseudo_vision_cnn:
  input_size: 64
  classes: 3
  return_layers:
    cnn.0: '1st'
    cnn.1: '2nd'
    cnn.2: '3rd'
  visualize_return_layers: true
  weights: '/home/ychau001/Desktop/best-results-epoch=5-val_acc1=0.82.ckpt'
  speed: 3.0

pseudo_vision_timm:
  input_size: 64
  timm:
    arch: "mobilenetv2_100"
    transfer_learning: false
    classes: 3
    drop_rate: 0.1
    in_chans: 1
  return_layers:
    blocks.0: '1st'
    blocks.1: '2nd'
    blocks.2: '3rd'
  visualize_return_layers: false
  weights: '/home/deepspeed/Downloads/best_64x64_34_1_pretrained.ckpt'
  speed: -0.9
  steering_angle: 0.2
  topic: '/vesc/low_level/ackermann_cmd_mux/input/navigation'